CREATE TABLE veterinarios (
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(60) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    telefone VARCHAR(11) UNIQUE NOT NULL,
    crmv VARCHAR(10) UNIQUE NOT NULL,
    status SMALLINT,

    PRIMARY KEY(id)

) ENGINE=InnoDB;